Only create source artifacts in centos online msft leg

diff --git a/eng/pipelines/templates/jobs/vmr-build.yml b/eng/pipelines/templates/jobs/vmr-build.yml
--- a/eng/pipelines/templates/jobs/vmr-build.yml
+++ b/eng/pipelines/templates/jobs/vmr-build.yml
@@ -114,6 +114,11 @@ parameters:
   type: boolean
   default: false
 
+# Create and publish the source artifacts
+- name: createSourceArtifacts
+  type: boolean
+  default: false
+
 # Skip the build step (this would be used when wanting to run tests only)
 - name: skipBuild
   type: boolean
@@ -565,10 +570,16 @@ jobs:
           if [[ '${{ parameters.buildFromArchive }}' == 'True' ]]; then
             customBuildArgs="$customBuildArgs --source-repository https://github.com/dotnet/dotnet"
             customBuildArgs="$customBuildArgs --source-version $(git -C "$(vmrPath)" rev-parse HEAD)"
-          else
-            # Enable source artifact creation only when building from a git repo.
-            # We strip the .git/ directory when building from archive,
-            # so it's not possible to create the artifacts in that mode.
+            if [[ '${{ parameters.createSourceArtifacts }}' == 'True' ]]; then
+              # Do not enable source artifact creation when not building from a git repo.
+              # We strip the .git/ directory when building from archive,
+              # so it's not possible to create the artifacts in that mode.
+              echo "Cannot create source artifacts when building from archive."
+              exit 1
+            fi
+          fi
+          
+          if [[ '${{ parameters.createSourceArtifacts }}' == 'True' ]]; then
             extraBuildProperties="$extraBuildProperties /p:CreateSourceArtifacts=true"
           fi
 
