Use a single job and fail immediately if PR title does not match

diff --git a/.github/workflows/protected-files-validation.yml b/.github/workflows/protected-files-validation.yml
--- a/.github/workflows/protected-files-validation.yml
+++ b/.github/workflows/protected-files-validation.yml
@@ -11,71 +11,12 @@ permissions:
   pull-requests: read
 
 jobs:
-  check-version-details:
+  check-protect-files:
     runs-on: ubuntu-22.04
     if: ${{ !startsWith(github.event.pull_request.title, 'rebootstrap') && !startsWith(github.event.pull_request.title, 're-bootstrap') && !startsWith(github.event.pull_request.title, 'release') && !startsWith(github.event.pull_request.title, '.NET Source-Build ') }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Fetch base branch from upstream
-        run: |
-          git fetch origin ${{ github.event.pull_request.base.ref }}
-
-      - name: Check for Version.Details.xml changes
+      - name: Protected File has Changes
         working-directory: ${{ needs.setup.outputs.repo-path }}
         run: |
-          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '^eng/Version.Details.xml$' >/dev/null; then
-            echo "Version.Details.xml has changed."
-            exit 1
-          else
-            echo "No changes in Version.Details.xml."
-          fi
-
-  check-versions-props:
-    runs-on: ubuntu-22.04
-    if: ${{ !startsWith(github.event.pull_request.title, 'rebootstrap') && !startsWith(github.event.pull_request.title, 're-bootstrap') && !startsWith(github.event.pull_request.title, 'release') && !startsWith(github.event.pull_request.title, '.NET Source-Build ') }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Fetch base branch from upstream
-        run: |
-          git fetch origin ${{ github.event.pull_request.base.ref }}
-
-      - name: Check for Versions.props changes
-        working-directory: ${{ needs.setup.outputs.repo-path }}
-        run: |
-          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '^eng/Versions.props$' >/dev/null; then
-            echo "Versions.props has changed."
-            exit 1
-          else
-            echo "No changes in Versions.props."
-          fi
-
-  check-eng-common:
-    runs-on: ubuntu-22.04
-    if: ${{ !startsWith(github.event.pull_request.title, 'rebootstrap') && !startsWith(github.event.pull_request.title, 're-bootstrap') && !startsWith(github.event.pull_request.title, 'release') && !startsWith(github.event.pull_request.title, '.NET Source-Build ') }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Fetch base branch from upstream
-        run: |
-          git fetch origin ${{ github.event.pull_request.base.ref }}
-
-      - name: Check for eng/common changes
-        working-directory: ${{ needs.setup.outputs.repo-path }}
-        run: |
-          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '^eng/common/' >/dev/null; then
-            echo "Changes detected in eng/common."
-            exit 1
-          else
-            echo "No changes in eng/common."
-          fi
+          echo "Cannot make changes to 'eng/Version.Details.xml', 'eng/Versions.props', and 'eng/common/' outside of a rebootstrap or .NET Source-Build release PR."
+          exit 1
